#!/usr/bin/env python3
"""
Patch a copy of speedscope's dist/release/index.html so it auto-loads an
embedded profile on open, instead of showing the drag-and-drop landing page.

How this works (reverse-engineered from speedscope's own CLI, bin/cli.mjs,
and its bundled app code):

  - speedscope's app only defines `window.speedscope.loadFileFromBase64`
    once it sees a truthy `localProfilePath` key in the URL hash fragment
    (this is the same mechanism the `speedscope <file>` CLI command uses:
    it writes a temp .js file and opens
    `index.html#localProfilePath=/tmp/....js`, which makes the app inject
    `<script src="file:///<path>">`).
  - That `file:///<path>` form is always an ABSOLUTE filesystem path, so it
    is not usable for a portable, double-click-anywhere bundle -- copying
    curlscope/ to a different machine or even a different directory would
    break it.
  - So instead: we set the hash to a harmless placeholder (any truthy
    string satisfies the gate and defines window.speedscope; the resulting
    injected `file:///placeholder` script 404s silently and has no other
    effect), and add our OWN inline bootstrap script that waits for
    `window.speedscope` to exist, then calls `loadFileFromBase64` directly
    with the profile embedded as base64 in a sibling .js file (relative
    path, so it works regardless of where the bundle directory is moved).
"""
import argparse
import base64
import json
import re
import sys
from pathlib import Path


BOOTSTRAP_JS_TEMPLATE = """\
// Auto-generated by dev/scripts/build_curlscope_bundle.py -- do not hand-edit.
// Embeds the profile data and feeds it to speedscope's loadFileFromBase64
// API once the app defines it (see build_curlscope_bundle.py for why).
(function() {{
  var PROFILE_FILENAME = {filename_json};
  var PROFILE_BASE64 = {base64_json};

  function tryLoad() {{
    if (window.speedscope && window.speedscope.loadFileFromBase64) {{
      window.speedscope.loadFileFromBase64(PROFILE_FILENAME, PROFILE_BASE64);
      return true;
    }}
    return false;
  }}

  if (!tryLoad()) {{
    var attempts = 0;
    var maxAttempts = 200; // ~10s at 50ms
    var iv = setInterval(function() {{
      attempts++;
      if (tryLoad() || attempts >= maxAttempts) {{
        clearInterval(iv);
      }}
    }}, 50);
  }}
}})();
"""


def patch_index_html(index_html_path: Path, bootstrap_js_filename: str):
    html = index_html_path.read_text()

    if "curlscope-bootstrap" in html:
        # Already patched by a previous run; strip the old injected bits so
        # this is idempotent (re-running the pipeline overwrites cleanly).
        html = re.sub(
            r"\s*<!-- curlscope-bootstrap:start -->.*?<!-- curlscope-bootstrap:end -->\n?",
            "\n",
            html,
            flags=re.DOTALL,
        )

    # Set a harmless truthy hash BEFORE the main speedscope bundle script
    # runs, so its componentDidMount sees hashParams.localProfilePath and
    # defines window.speedscope. Must be a same-document hash change (no
    # navigation), applied prior to <script src="speedscope-....js">.
    injection = (
        "\n    <!-- curlscope-bootstrap:start -->\n"
        "    <script>\n"
        "      // Any truthy value satisfies speedscope's internal check that\n"
        "      // defines window.speedscope.loadFileFromBase64 on page load.\n"
        "      if (!location.hash) { location.hash = '#localProfilePath=curlscope'; }\n"
        "    </script>\n"
        f'    <script src="{bootstrap_js_filename}"></script>\n'
        "    <!-- curlscope-bootstrap:end -->\n"
    )

    if "<script src=" in html:
        html = html.replace(
            '<script src="', injection + '    <script src="', 1
        )
    else:
        html = html.replace("</body>", injection + "  </body>")

    index_html_path.write_text(html)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--speedscope-dir", required=True,
                     help="directory containing speedscope's index.html "
                          "(a copy of dist/release, already placed at the "
                          "destination)")
    ap.add_argument("--profile-json", required=True,
                     help="path to the .speedscope.json profile to embed")
    ap.add_argument("--profile-filename", required=True,
                     help="filename to report to speedscope as the "
                          "'imported' file name (cosmetic, shown in the UI)")
    args = ap.parse_args()

    speedscope_dir = Path(args.speedscope_dir)
    index_html = speedscope_dir / "index.html"
    if not index_html.exists():
        sys.exit(f"error: {index_html} not found")

    profile_path = Path(args.profile_json)
    profile_bytes = profile_path.read_bytes()

    # Sanity check it's at least valid JSON with the expected shape before
    # embedding, so a bad conversion fails loudly here instead of silently
    # producing a bundle that shows a blank speedscope UI.
    try:
        doc = json.loads(profile_bytes)
    except json.JSONDecodeError as e:
        sys.exit(f"error: {profile_path} is not valid JSON: {e}")
    if "profiles" not in doc or "shared" not in doc:
        sys.exit(f"error: {profile_path} does not look like a speedscope "
                  f"profile (missing 'profiles'/'shared' keys)")
    nframes = len(doc.get("shared", {}).get("frames", []))
    nsamples = sum(len(p.get("samples", [])) for p in doc["profiles"])
    print(f"Embedding profile: {nframes} frames, {nsamples} stack samples, "
          f"{len(profile_bytes)} bytes", file=sys.stderr)

    b64 = base64.b64encode(profile_bytes).decode("ascii")

    bootstrap_js_filename = "curlscope-profile.js"
    bootstrap_js = BOOTSTRAP_JS_TEMPLATE.format(
        filename_json=json.dumps(args.profile_filename),
        base64_json=json.dumps(b64),
    )
    (speedscope_dir / bootstrap_js_filename).write_text(bootstrap_js)

    # Also copy the raw JSON alongside for archival / re-import elsewhere,
    # not required for auto-load but useful to have as a plain artifact.
    (speedscope_dir / "profile.speedscope.json").write_bytes(profile_bytes)

    patch_index_html(index_html, bootstrap_js_filename)
    print(f"Patched {index_html}", file=sys.stderr)
    print(f"Wrote {speedscope_dir / bootstrap_js_filename} "
          f"({len(bootstrap_js)} bytes)", file=sys.stderr)
    print(f"Wrote {speedscope_dir / 'profile.speedscope.json'} "
          f"({len(profile_bytes)} bytes, archival copy)", file=sys.stderr)


if __name__ == "__main__":
    main()
